language: python
python:
  - "3.3"
virtualenv:
  system_site_packages: true
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pep8
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script:
  - pwd
  - coverage run --source=sym setup.py test
  - coveralls
